openapi: "3.0.0"
info:
  version: 1.0.0
  title: Add Numbers API
  description: This API is provided by The Content Gym as an example - Calculus Cloud - to add two numbers. The code of the REST API is available at [GitHub](https://github.com/TheContentGym/CreateRestAPIAddTwoNumbers).
servers:
  - url: http://localhost:5000  
    description: base URL or the URL for making the REST API calls
paths:
  /add:
    get:
      summary: Add two numbers.
      description: Perform addition of two numbers and get the result.
      parameters:
        - name: number1
          in: query
          required: true
          description: The first number to be added.
          schema:
            type: number
        - name: number2
          in: query
          required: true
          description: The second number to be added.
          schema:
            type: number
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                    description: The result of the addition operation.
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message for missing or invalid input.