openapi: "3.0.0"
info:
  title: Add Numbers API
  version: 1.0.0
  description: This is The Content Gym's example API [Calculus Cloud example] to add two numbers. The code of the REST API is available at [GitHub](https://github.com/TheContentGym/CreateRestAPIAddTwoNumbers).

servers:
  - url: http://127.0.0.1:5000

paths:
  /add:
    post:
      summary: Add two numbers
      description: Perform addition of two numbers and get the result
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                number1:
                  type: number
                  description: The first number to be added
                number2:
                  type: number
                  description: The second number to be added
              required:
                - number1
                - number2
              example:
                number1: 9
                number2: 99
      responses:
        '200':
          description: Addition successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                    description: The result of the addition
              example:
                result: 108
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message indicating the cause of the bad request
              example:
                message: "Both 'number1' and 'number2' must be provided as numbers."
