#
name: Lint Python Code

on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        # This step clones the repository to the build server.

      - name: Set up Python environment
        run: python -m venv venv && source venv/bin/activate
        # This step sets up a Python environment.

      - name: Install Flake8
        run: pip install flake8
        # This step installs the Flake8 linter tool.

      - name: Lint code
        run: flake8 .
        # This step runs the Flake8 linter tool on your code.
